In [1]:
import torch
from PIL import Image
import numpy as np

In [2]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
v =torch.ones([2,3])
v

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
# change shape use view()
v.view(2,-1)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
from torchvision import transforms
image_to_tensor= transforms.ToTensor()

In [ ]:
image_to_tensor(v)
#in tensor the color channel come first
#tensor to image use
tensor_2_image =transforms.ToPILImage()


### Tensor hands-on segment

In [21]:
a = torch.arange(10)
b=torch.arange(10)*10

In [22]:
print(a)
print(b)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [23]:
a+b

tensor([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [24]:
a.shape

torch.Size([10])

In [25]:
b.shape

torch.Size([10])

In [29]:
#make order 2  tensor
a[None].shape



torch.Size([1, 10])

In [30]:
# add the dimension to the end
a[:,None].shape

torch.Size([10, 1])

In [35]:
a[None,:,None].shape

torch.Size([1, 10, 1])

In [36]:
a[None,:,None]

tensor([[[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]])

In [37]:
c =a[None,:]

In [39]:
c.shape

torch.Size([1, 10])

In [40]:
c[0,:].shape

torch.Size([10])

#### Broadcasting

In [41]:
#broadcasting
torch.ones(3,2)+10

tensor([[11., 11.],
        [11., 11.],
        [11., 11.]])

In [42]:
torch.ones(2,2)+torch.ones(2,3)

RuntimeError: ignored

In [44]:
torch.ones(3,1)+torch.ones(1,3)
 # broadcasting: the first tensor  will be replicated  along the second dimension.
#The second tensor will be
#replicated three times along the first dimension, then the two tensors have the same shape.

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [46]:
a[None,:]+b[:,None]

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [49]:
a[None,:]

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [51]:
a[None,:].repeat(10,1)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [52]:
b[:,None].repeat(1,10)

tensor([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
        [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
        [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
        [40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
        [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
        [60, 60, 60, 60, 60, 60, 60, 60, 60, 60],
        [70, 70, 70, 70, 70, 70, 70, 70, 70, 70],
        [80, 80, 80, 80, 80, 80, 80, 80, 80, 80],
        [90, 90, 90, 90, 90, 90, 90, 90, 90, 90]])

In [53]:
a[None,:].repeat(10,1)+b[:,None].repeat(1,10)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [54]:
a[None,:]+b[:,None]

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [55]:
a[None,:]*b[:,None]

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
        [  0,  20,  40,  60,  80, 100, 120, 140, 160, 180],
        [  0,  30,  60,  90, 120, 150, 180, 210, 240, 270],
        [  0,  40,  80, 120, 160, 200, 240, 280, 320, 360],
        [  0,  50, 100, 150, 200, 250, 300, 350, 400, 450],
        [  0,  60, 120, 180, 240, 300, 360, 420, 480, 540],
        [  0,  70, 140, 210, 280, 350, 420, 490, 560, 630],
        [  0,  80, 160, 240, 320, 400, 480, 560, 640, 720],
        [  0,  90, 180, 270, 360, 450, 540, 630, 720, 810]])

In [56]:
a[None,:]-b[:,None]

tensor([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1],
        [-20, -19, -18, -17, -16, -15, -14, -13, -12, -11],
        [-30, -29, -28, -27, -26, -25, -24, -23, -22, -21],
        [-40, -39, -38, -37, -36, -35, -34, -33, -32, -31],
        [-50, -49, -48, -47, -46, -45, -44, -43, -42, -41],
        [-60, -59, -58, -57, -56, -55, -54, -53, -52, -51],
        [-70, -69, -68, -67, -66, -65, -64, -63, -62, -61],
        [-80, -79, -78, -77, -76, -75, -74, -73, -72, -71],
        [-90, -89, -88, -87, -86, -85, -84, -83, -82, -81]])

In [57]:
a[None,:]/b[:,None] # due to the zeros

tensor([[   nan,    inf,    inf,    inf,    inf,    inf,    inf,    inf,    inf,
            inf],
        [0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
         0.9000],
        [0.0000, 0.0500, 0.1000, 0.1500, 0.2000, 0.2500, 0.3000, 0.3500, 0.4000,
         0.4500],
        [0.0000, 0.0333, 0.0667, 0.1000, 0.1333, 0.1667, 0.2000, 0.2333, 0.2667,
         0.3000],
        [0.0000, 0.0250, 0.0500, 0.0750, 0.1000, 0.1250, 0.1500, 0.1750, 0.2000,
         0.2250],
        [0.0000, 0.0200, 0.0400, 0.0600, 0.0800, 0.1000, 0.1200, 0.1400, 0.1600,
         0.1800],
        [0.0000, 0.0167, 0.0333, 0.0500, 0.0667, 0.0833, 0.1000, 0.1167, 0.1333,
         0.1500],
        [0.0000, 0.0143, 0.0286, 0.0429, 0.0571, 0.0714, 0.0857, 0.1000, 0.1143,
         0.1286],
        [0.0000, 0.0125, 0.0250, 0.0375, 0.0500, 0.0625, 0.0750, 0.0875, 0.1000,
         0.1125],
        [0.0000, 0.0111, 0.0222, 0.0333, 0.0444, 0.0556, 0.0667, 0.0778, 0.0889,
         0.1000]])

In [65]:
torch.ones(2,5)+torch.ones(5,2)

RuntimeError: ignored

In [61]:
torch.ones(2,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [63]:
torch.ones(5,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

##Rules of Broadcasting
Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

#### Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
####Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
####Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

link
 [link text](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)

